version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Uses the production Dockerfile
    ports:
      - "80:80"  # Serve the app on HTTP port 80
    restart: always  # Automatically restart the container in case of crashes
